services:
  - type: web
    name: zunaisha-islamic-institute
    runtime: node
    rootDir: Zunaisha_Islamic_Institute
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false   # you will paste this in Render dashboard manually
    autoDeploy: true
